language: node_js
node_js:
  - "10"
cache:
  yarn: true
before_install:
  - npm i -g yarn
install:
  - yarn
script:
  - yarn build
deploy:
  provider: script
  skip_cleanup: true
  script:
    - git config --global user.name "${GH_NAME}"
    - git config --global user.email "${GH_EMAIL}"
    - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
    - yarn && GIT_USER="${GH_NAME}" yarn deploy
    - openssl aes-256-cbc -K $encrypted_2d8c63ef40a5_key -iv $encrypted_2d8c63ef40a5_iv -in id_rsa.enc -out id_rsa -d
    - scp -i id_rsa -r build/* "${SERVER_IP}":"${DOC_DIR}"
  on:
    branch: master
